"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { FiArrowLeft, FiCalendar, FiChevronRight, FiRefreshCw, FiSearch, FiTrendingUp, FiUsers, FiX } from "react-icons/fi";
import { supabase } from "@/lib/supabase";

type Student={id:string;student_name:string|null;student_id:string|null;course:string|null;father_name:string|null;guardian_name:string|null};
type Ledger={id:string;admission_id:string;fee_month:string;amount_due:number;amount_paid:number;payment_date:string|null;payment_method:string|null;receipt_number:string|null;remarks:string|null};
type Due={student:Student;due:number;paid:number;billed:number;months:number};
type Collection={student:Student;amount:number;payment_date:string;method:string;receipt:string;month:string;remarks:string};

const money=(v:number)=>`₹${Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:0})}`;
const monthName=(v:string)=>new Date(`${v.slice(0,7)}-01T00:00:00`).toLocaleDateString("en-IN",{month:"long",year:"numeric"});
const shortDate=(v:string|null)=>v?new Date(v.includes("T")?v:`${v}T00:00:00`).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"—";
const monthKey=(v:string|null)=>v?String(v).slice(0,7):"";

export default function FeeAccountPage(){
 const router=useRouter();
 const [students,setStudents]=useState<Student[]>([]),[ledger,setLedger]=useState<Ledger[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(""),[q,setQ]=useState(""),[collectionOpen,setCollectionOpen]=useState(false);
 const [month,setMonth]=useState(new Date().toISOString().slice(0,7));
 const load=async()=>{setError("");setRefreshing(true);try{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/admin");return}const {data:isAdmin,error:ae}=await supabase.rpc("is_admin");if(ae||isAdmin!==true){await supabase.auth.signOut();router.replace("/admin");return}
  const {data:s,error:se}=await supabase.from("admissions").select("id,student_name,student_id,course,father_name,guardian_name").eq("status","approved").eq("account_status","approved").order("student_name");if(se)throw se;const ss=(s||[]) as Student[];setStudents(ss);
  if(ss.length){await Promise.all(ss.map(x=>supabase.rpc("ensure_student_fee_ledger",{p_admission_id:x.id})));}
  const ids=ss.map(x=>x.id);if(ids.length){const {data:l,error:le}=await supabase.from("student_fee_ledger").select("id,admission_id,fee_month,amount_due,amount_paid,payment_date,payment_method,receipt_number,remarks").in("admission_id",ids).order("fee_month",{ascending:false});if(le)throw le;setLedger((l||[]) as Ledger[])}else setLedger([]);
 }catch(e:any){setError(e?.message||"Unable to load fee account data.")}finally{setLoading(false);setRefreshing(false)}};
 useEffect(()=>{load()},[]);
 const byStudent=useMemo(()=>{const m=new Map<string,Ledger[]>();for(const x of ledger){const a=m.get(x.admission_id)||[];a.push(x);m.set(x.admission_id,a)}return m},[ledger]);
 const dues=useMemo<Due[]>(()=>students.map(s=>{const rows=byStudent.get(s.id)||[];const billed=rows.reduce((a,x)=>a+Number(x.amount_due||0),0);const paid=rows.reduce((a,x)=>a+Number(x.amount_paid||0),0);return{student:s,due:Math.max(0,billed-paid),paid,billed,months:rows.filter(x=>Number(x.amount_due||0)>Number(x.amount_paid||0)).length}}).filter(x=>x.due>0).filter(x=>`${x.student.student_name||""} ${x.student.student_id||""} ${x.student.course||""}`.toLowerCase().includes(q.trim().toLowerCase())).sort((a,b)=>b.due-a.due||String(a.student.student_name).localeCompare(String(b.student.student_name))),[students,byStudent,q]);
 const totalDue=useMemo(()=>students.reduce((sum,s)=>{const rows=byStudent.get(s.id)||[];return sum+rows.reduce((a,x)=>a+Math.max(0,Number(x.amount_due||0)-Number(x.amount_paid||0)),0)},0),[students,byStudent]);
 const collection=useMemo<Collection[]>(()=>{const out:Collection[]=[];for(const l of ledger){if(!l.payment_date||String(l.payment_date).slice(0,7)!==month||Number(l.amount_paid||0)<=0)continue;const s=students.find(x=>x.id===l.admission_id);if(!s)continue;out.push({student:s,amount:Number(l.amount_paid||0),payment_date:l.payment_date,method:l.payment_method||"—",receipt:l.receipt_number||"—",month:l.fee_month,remarks:l.remarks||""})}return out.sort((a,b)=>b.payment_date.localeCompare(a.payment_date))},[ledger,students,month]);
 const collectionTotal=collection.reduce((a,x)=>a+x.amount,0);
 const months=useMemo(()=>{const set=new Set<string>();ledger.forEach(x=>x.payment_date&&set.add(String(x.payment_date).slice(0,7)));set.add(new Date().toISOString().slice(0,7));return [...set].sort().reverse()},[ledger]);
 const monthOptions=[...new Set([month,...months])];
 if(loading)return <main className="flex min-h-screen items-center justify-center bg-slate-50"><div className="text-center"><FiRefreshCw className="mx-auto animate-spin text-4xl text-green-700"/><p className="mt-3 font-bold text-slate-600">Loading Fee & Account...</p></div></main>;
 return <main className="min-h-screen bg-[#f4f7f5] text-slate-900">
  <header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 backdrop-blur-xl shadow-sm"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4 sm:px-6"><div className="flex items-center gap-3"><img src="/mmbb-logo.svg" className="h-12 w-12 rounded-full" alt="MMBB"/><div><p className="text-[10px] font-black uppercase tracking-[.25em] text-green-700">Madrasa Majmaul Bahrain Bijol</p><h1 className="text-2xl font-black">Fee & Account</h1></div></div><div className="flex gap-2"><button onClick={()=>load()} disabled={refreshing} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2.5 font-bold disabled:opacity-50"><FiRefreshCw className={refreshing?"animate-spin":""}/><span className="hidden sm:inline">Refresh</span></button><button onClick={()=>router.push("/admin/dashboard")} className="inline-flex items-center gap-2 rounded-xl bg-green-700 px-4 py-2.5 font-black text-white"><FiArrowLeft/> Dashboard</button></div></div></header>
  <section className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:py-9">
   <div className="rounded-[30px] bg-gradient-to-br from-emerald-950 via-emerald-800 to-emerald-600 p-7 text-white shadow-xl sm:p-9"><p className="text-xs font-black uppercase tracking-[.3em] text-emerald-200">Accounts Overview</p><h2 className="mt-2 text-4xl font-black">Fee Collection & Outstanding Due</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-emerald-50">A clean financial overview of active students. Students with no outstanding due are automatically hidden from the Due list.</p><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border border-white/10 bg-white/10 p-5"><p className="text-xs font-bold text-emerald-200">TOTAL OUTSTANDING DUE</p><p className="mt-2 text-3xl font-black">{money(totalDue)}</p><p className="mt-1 text-xs text-emerald-100">All active students</p></div><button onClick={()=>setCollectionOpen(true)} className="rounded-2xl border border-white/10 bg-white/10 p-5 text-left transition hover:bg-white/15"><p className="text-xs font-bold text-emerald-200">THIS MONTH COLLECTION</p><p className="mt-2 text-3xl font-black">{money(collectionTotal)}</p><p className="mt-1 text-xs text-emerald-100">{monthName(month)} • {collection.length} payment entries • Click to view</p></button><div className="rounded-2xl border border-white/10 bg-white/10 p-5"><p className="text-xs font-bold text-emerald-200">ACTIVE STUDENTS</p><p className="mt-2 text-3xl font-black">{students.length}</p><p className="mt-1 text-xs text-emerald-100">Approved & active</p></div><div className="rounded-2xl border border-white/10 bg-white/10 p-5"><p className="text-xs font-bold text-emerald-200">STUDENTS WITH DUE</p><p className="mt-2 text-3xl font-black">{dues.length}</p><p className="mt-1 text-xs text-emerald-100">After search filter</p></div></div></div>
   {error&&<div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 font-bold text-red-700">{error}</div>}
   <div className="mt-6 grid gap-4 lg:grid-cols-[1fr_230px]"><div className="rounded-2xl border bg-white p-4 shadow-sm"><div className="relative"><FiSearch className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search student with due..." className="w-full rounded-xl border bg-slate-50 py-3.5 pl-11 pr-4 font-medium outline-none focus:border-green-600 focus:bg-white focus:ring-4 focus:ring-green-100"/></div></div><label className="rounded-2xl border bg-white p-4 shadow-sm"><span className="mb-2 flex items-center gap-2 text-xs font-black uppercase tracking-wider text-slate-500"><FiCalendar/> Collection Month</span><select value={month} onChange={e=>{setMonth(e.target.value);setCollectionOpen(false)}} className="w-full rounded-xl border px-3 py-2.5 font-bold"><option value={new Date().toISOString().slice(0,7)}>{monthName(new Date().toISOString().slice(0,7))}</option>{monthOptions.filter(x=>x!==new Date().toISOString().slice(0,7)).map(x=><option key={x} value={x}>{monthName(x)}</option>)}</select></label></div>
   <div className="mt-6 rounded-3xl border bg-white shadow-sm overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b bg-slate-50 px-5 py-4"><div><h3 className="text-xl font-black">Outstanding Due</h3><p className="text-sm text-slate-500">Only students whose current ledger has unpaid balance are shown.</p></div><div className="rounded-xl bg-red-50 px-4 py-2 font-black text-red-700">{money(totalDue)} total due</div></div>{dues.length?<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-emerald-900 text-white"><tr><th className="p-3 text-left">#</th><th className="p-3 text-left">Student</th><th className="p-3 text-left">Student ID</th><th className="p-3 text-left">Course</th><th className="p-3 text-right">Outstanding Due</th><th className="p-3 text-center">Unpaid Months</th><th className="p-3"></th></tr></thead><tbody>{dues.map((x,i)=><tr key={x.student.id} className="border-b last:border-0 hover:bg-emerald-50/40"><td className="p-4 font-black text-slate-400">{i+1}</td><td className="p-4 font-black">{x.student.student_name}</td><td className="p-4 font-bold text-green-700">{x.student.student_id||"—"}</td><td className="p-4">{x.student.course||"—"}</td><td className="p-4 text-right text-lg font-black text-red-700">{money(x.due)}</td><td className="p-4 text-center font-bold">{x.months}</td><td className="p-4 text-right"><button onClick={()=>router.push(`/admin/students/${encodeURIComponent(x.student.student_id||x.student.id)}`)} className="inline-flex items-center gap-1 rounded-lg bg-green-50 px-3 py-2 font-black text-green-700 hover:bg-green-100">Profile <FiChevronRight/></button></td></tr>)}</tbody></table></div>:<div className="p-14 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-emerald-100 text-2xl text-emerald-700">✓</div><h3 className="mt-4 text-xl font-black">No outstanding dues</h3><p className="mt-1 text-slate-500">All active students currently have a zero outstanding balance.</p></div>}</div>
   <div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase tracking-wider text-slate-400">Selected Month</p><p className="mt-2 text-xl font-black">{monthName(month)}</p><p className="mt-1 text-sm text-slate-500">Collection shown above</p></div><button onClick={()=>setCollectionOpen(true)} className="rounded-2xl border bg-white p-5 text-left hover:border-green-300 hover:shadow-sm"><p className="text-xs font-black uppercase tracking-wider text-green-700">Collection Details</p><p className="mt-2 text-xl font-black">{collection.length} payment entries</p><p className="mt-1 text-sm text-slate-500">Click to see student-wise payments, date, method and receipt.</p></button><div className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase tracking-wider text-slate-400">Collection Total</p><p className="mt-2 text-xl font-black text-green-700">{money(collectionTotal)}</p><p className="mt-1 text-sm text-slate-500">Payments recorded in {monthName(month)}</p></div></div>
  </section>
  {collectionOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" onClick={()=>setCollectionOpen(false)}><div className="max-h-[90vh] w-full max-w-5xl overflow-hidden rounded-3xl bg-white shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between border-b p-5"><div><p className="text-xs font-black uppercase tracking-[.2em] text-green-700">Fee Collection</p><h2 className="text-2xl font-black">{monthName(month)}</h2><p className="text-sm text-slate-500">{collection.length} payment entries • Total {money(collectionTotal)}</p></div><button onClick={()=>setCollectionOpen(false)} className="rounded-xl border p-2.5"><FiX/></button></div><div className="max-h-[65vh] overflow-auto">{collection.length?<table className="w-full min-w-[760px] text-sm"><thead className="sticky top-0 bg-emerald-900 text-white"><tr><th className="p-3 text-left">Student</th><th className="p-3 text-left">Student ID</th><th className="p-3 text-left">Fee Month</th><th className="p-3 text-left">Payment Date</th><th className="p-3 text-left">Method</th><th className="p-3 text-left">Receipt</th><th className="p-3 text-right">Amount</th></tr></thead><tbody>{collection.map((x,i)=><tr key={`${x.student.id}-${x.payment_date}-${i}`} className="border-b"><td className="p-4 font-black">{x.student.student_name}</td><td className="p-4 font-bold text-green-700">{x.student.student_id||"—"}</td><td className="p-4">{monthName(x.month)}</td><td className="p-4">{shortDate(x.payment_date)}</td><td className="p-4">{x.method}</td><td className="p-4">{x.receipt}</td><td className="p-4 text-right font-black text-green-700">{money(x.amount)}</td></tr>)}</tbody></table>:<div className="p-14 text-center text-slate-500"><p className="font-black text-slate-800">No fee collection recorded</p><p className="mt-1">There are no payments with a payment date in {monthName(month)}.</p></div>}</div></div></div>}
 </main>;
}
