"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { supabase } from "../lib/supabase";

const authEmail = (id: string) => `${id.trim().toLowerCase()}@student.mmbb.local`;

const inputClass = "mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3.5 text-base font-semibold text-slate-900 caret-green-700 shadow-sm outline-none transition placeholder:text-slate-400 focus:border-green-600 focus:ring-4 focus:ring-green-100";

export default function LoginPage() {
  const [studentId,setStudentId]=useState(""); const [password,setPassword]=useState(""); const [loginError,setLoginError]=useState(""); const [loginLoading,setLoginLoading]=useState(false);
  const [mustChange,setMustChange]=useState(false); const [newPassword,setNewPassword]=useState(""); const [confirmPassword,setConfirmPassword]=useState(""); const [passwordMessage,setPasswordMessage]=useState(""); const [passwordLoading,setPasswordLoading]=useState(false);
  const [applicationNumber,setApplicationNumber]=useState(""); const [mobile,setMobile]=useState(""); const [statusResult,setStatusResult]=useState<any>(null); const [statusError,setStatusError]=useState(""); const [statusLoading,setStatusLoading]=useState(false);

  async function login(e:FormEvent){e.preventDefault();setLoginLoading(true);setLoginError("");try{const id=studentId.trim().toUpperCase();if(!/^MMBB[A-Z]{3}\d{4}$/.test(id))throw new Error("Please enter a valid Student ID.");const {data,error}=await supabase.auth.signInWithPassword({email:authEmail(id),password});if(error||!data.user)throw new Error("Student ID or password is incorrect.");const {data:account,error:accountError}=await supabase.from("student_accounts").select("student_id,password_created,account_status").eq("auth_user_id",data.user.id).maybeSingle();if(accountError)throw accountError;if(!account||account.account_status!=="approved"){await supabase.auth.signOut();throw new Error("Your student account is inactive or not active. Please contact the Madrasa office.");}if(!account.password_created||data.user.user_metadata?.must_change_password)setMustChange(true);else window.location.href="/student/dashboard";}catch(err){setLoginError(err instanceof Error?err.message:"Login failed.");}finally{setLoginLoading(false);}}

  async function changePassword(e:FormEvent){e.preventDefault();setPasswordMessage("");if(newPassword.length<8){setPasswordMessage("New password must be at least 8 characters.");return}if(newPassword!==confirmPassword){setPasswordMessage("Passwords do not match.");return}setPasswordLoading(true);try{const {data,error}=await supabase.functions.invoke("student-password",{body:{newPassword}});if(error||data?.error)throw new Error(data?.error||error?.message||"Password update failed.");setPasswordMessage("Password updated. Opening your student portal...");setTimeout(()=>window.location.href="/student/dashboard",700)}catch(err){setPasswordMessage(err instanceof Error?err.message:"Password update failed.");}finally{setPasswordLoading(false);}}

  async function checkStatus(e:FormEvent){e.preventDefault();setStatusLoading(true);setStatusError("");setStatusResult(null);try{const {data,error}=await supabase.functions.invoke("student-application-status",{body:{applicationNumber,mobile}});if(error||data?.error)throw new Error(data?.error||error?.message||"Unable to check status.");setStatusResult(data);}catch(err){setStatusError(err instanceof Error?err.message:"Unable to check status.");}finally{setStatusLoading(false);}}

  return <><Navbar/><section className="bg-gradient-to-br from-green-950 via-green-800 to-green-600 px-6 pb-20 pt-36 text-center text-white"><p className="text-sm font-bold uppercase tracking-[5px] text-green-200">Student Portal</p><h1 className="mt-5 text-4xl font-extrabold sm:text-5xl md:text-6xl">Student Login</h1><p className="mx-auto mt-5 max-w-3xl text-green-100">Secure access to your personal profile, attendance, results, fees and official student records.</p></section>
  <section className="bg-slate-50 px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-2">
    <div className="rounded-3xl bg-white p-7 shadow-xl ring-1 ring-slate-100 sm:p-9"><div className="mb-7 flex items-center gap-4 border-b border-slate-100 pb-6"><img src="/mmbb-logo.svg" alt="MMBB" className="h-16 w-16 rounded-full"/><div><p className="text-xs font-black uppercase tracking-[3px] text-green-700">Madrasa Majmaul Bahrain Bijol</p><h2 className="mt-1 text-2xl font-black">{mustChange?"Set Permanent Password":"Student Login"}</h2></div></div>
      {!mustChange?<form onSubmit={login} className="space-y-5"><div><label className="font-bold text-slate-800">Student ID</label><input value={studentId} onChange={e=>setStudentId(e.target.value.toUpperCase())} className={inputClass} placeholder="MMBBMDR0802" autoComplete="username"/></div><div><label className="font-bold text-slate-800">Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} className={inputClass} placeholder="Enter your password" autoComplete="current-password"/></div>{loginError&&<div className="rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{loginError}</div>}<button disabled={loginLoading} className="w-full rounded-xl bg-green-800 py-4 font-black text-white shadow-lg transition hover:bg-green-900 disabled:opacity-60">{loginLoading?"Signing in...":"Login to Student Portal"}</button></form>:<form onSubmit={changePassword} className="space-y-5"><div className="rounded-2xl bg-amber-50 p-4 text-sm leading-6 text-amber-900"><strong>First login:</strong> your temporary DOB password was accepted. Create your permanent password now.</div><div><label className="font-bold text-slate-800">New Password</label><input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} className={inputClass} placeholder="Minimum 8 characters" autoComplete="new-password"/></div><div><label className="font-bold text-slate-800">Confirm New Password</label><input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} className={inputClass} placeholder="Re-enter your new password" autoComplete="new-password"/></div>{passwordMessage&&<div className="rounded-xl bg-green-50 p-4 text-sm font-bold text-green-800">{passwordMessage}</div>}<button disabled={passwordLoading} className="w-full rounded-xl bg-green-800 py-4 font-black text-white disabled:opacity-60">{passwordLoading?"Saving...":"Set Permanent Password"}</button></form>}
      <div className="mt-7 rounded-2xl bg-slate-50 p-5 text-sm leading-6 text-slate-600"><strong className="text-slate-900">Forgot your password?</strong> Contact the Madrasa office with your Student ID and registered details. After verification, the office can reset it to your DOB temporary password.</div>
    </div>
    <div className="rounded-3xl bg-white p-7 shadow-xl ring-1 ring-slate-100 sm:p-9"><div className="mb-7 flex items-center gap-4 border-b border-slate-100 pb-6"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-green-50 text-2xl">🔎</div><div><p className="text-xs font-black uppercase tracking-[3px] text-green-700">Admission Office</p><h2 className="mt-1 text-2xl font-black">Check Your Application</h2></div></div><p className="mt-3 text-slate-600">Enter your application number and primary registered mobile number.</p><form onSubmit={checkStatus} className="mt-8 space-y-5"><div><label className="font-bold text-slate-800">Application Number</label><input value={applicationNumber} onChange={e=>setApplicationNumber(e.target.value.toUpperCase())} className={inputClass} placeholder="MMBB-2026-123456"/></div><div><label className="font-bold text-slate-800">Primary Registered Mobile</label><input value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,"").slice(0,10))} inputMode="numeric" maxLength={10} className={inputClass} placeholder="10-digit mobile number"/></div>{statusError&&<div className="rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{statusError}</div>}<button disabled={statusLoading} className="w-full rounded-xl border-2 border-green-800 py-3.5 font-black text-green-800 transition hover:bg-green-50 disabled:opacity-60">{statusLoading?"Checking...":"Check Application Status"}</button></form>
      {statusResult&&<div className="mt-7 overflow-hidden rounded-2xl border border-green-200 bg-green-50"><div className="flex items-center gap-4 border-b border-green-200 bg-white/80 p-4"><img src="/mmbb-logo.svg" alt="MMBB" className="h-12 w-12 rounded-full"/><div className="min-w-0 flex-1"><p className="text-xs font-black uppercase tracking-[2px] text-green-700">Student Application Record</p><h3 className="mt-1 truncate text-xl font-black text-slate-900">{statusResult.studentName}</h3></div><span className={`rounded-full px-3 py-1 text-xs font-black uppercase ${statusResult.accountStatus==="inactive"?"bg-red-100 text-red-700":"bg-green-100 text-green-800"}`}>{String(statusResult.status).replace("_"," ")}</span></div><div className="p-5"><p className="text-sm leading-6 text-slate-700">{statusResult.message}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-white p-3"><p className="text-xs text-slate-500">Application Number</p><p className="font-black text-slate-900">{statusResult.applicationNumber}</p></div><div className="rounded-xl bg-white p-3"><p className="text-xs text-slate-500">Course</p><p className="font-black text-slate-900">{statusResult.course||"—"}</p></div></div>{statusResult.approved&&statusResult.accountStatus!=="inactive"&&<div className="mt-4 rounded-xl bg-green-900 p-5 text-white"><p className="text-xs font-black uppercase tracking-[2px] text-green-200">Admission Approved</p><p className="mt-1 text-lg font-black">Student ID: {statusResult.studentId}</p><p className="mt-2 text-lg font-black">Temporary Password: {statusResult.temporaryPassword}</p><p className="mt-2 text-xs leading-5 text-green-100">Use these credentials to login. You will be required to create a permanent password on first login.</p></div>}</div></div>}
      <Link href="/admission" className="mt-6 inline-flex w-full justify-center rounded-xl bg-slate-900 py-3.5 font-black text-white">Apply for Admission</Link>
    </div>
  </div></section><Footer/></>;
}
