"use client";

import { useEffect, useState } from "react";
import { supabase, uploadTopperImage, deleteTopperImage } from "../../lib/supabase";

type Topper = { id: string; student_name: string; rank: string; description: string | null; photo_url: string | null; exam_name: string | null; exam_date: string | null; course: string | null; active: boolean; created_at: string; };
type Form = { student_name: string; rank: string; description: string; exam_name: string; exam_date: string; course: string; photo_url: string; active: boolean; };
const emptyForm = (): Form => ({ student_name: "", rank: "", description: "", exam_name: "", exam_date: "", course: "", photo_url: "", active: false });

export default function ToppersAdminPage() {
  const [items, setItems] = useState<Topper[]>([]); const [form, setForm] = useState<Form>(emptyForm()); const [editing, setEditing] = useState<Topper | null>(null); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState(""); const [showForm, setShowForm] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");

  useEffect(() => { load(); }, []);
  async function load() { setLoading(true); const { data, error } = await supabase.from("toppers").select("*").order("created_at", { ascending: false }); if (error) setError(error.message); else setItems((data || []) as Topper[]); setLoading(false); }
  function openAdd() { setEditing(null); setForm(emptyForm()); setFile(null); setPreview(""); setMessage(""); setError(""); setShowForm(true); }
  function openEdit(item: Topper) { setEditing(item); setForm({ student_name:item.student_name, rank:item.rank, description:item.description||"", exam_name:item.exam_name||"", exam_date:item.exam_date||"", course:item.course||"", photo_url:item.photo_url||"", active:item.active }); setFile(null); setPreview(""); setMessage(""); setError(""); setShowForm(true); }
  function closeForm() { if (!saving) { setShowForm(false); setEditing(null); setFile(null); setPreview(""); } }
  function chooseFile(f: File | null) { setFile(f); if (f) setPreview(URL.createObjectURL(f)); else setPreview(""); }

  async function save(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(""); setMessage(""); try {
    if (!form.student_name.trim() || !form.rank.trim()) throw new Error("Student name aur rank zaroor likhein.");
    let photo = form.photo_url;
    if (file) photo = await uploadTopperImage(file);
    const payload = { student_name:form.student_name.trim(), rank:form.rank.trim(), description:form.description.trim()||null, exam_name:form.exam_name.trim()||null, exam_date:form.exam_date||null, course:form.course.trim()||null, photo_url:photo||null, active:form.active, updated_at:new Date().toISOString() };
    if (editing) { const { error } = await supabase.from("toppers").update(payload).eq("id", editing.id); if (error) throw error; if (file && editing.photo_url) await deleteTopperImage(editing.photo_url).catch(()=>{}); setMessage("Topper successfully update ho gaya."); }
    else { const { error } = await supabase.from("toppers").insert(payload); if (error) throw error; setMessage("Topper successfully add ho gaya."); }
    await load(); setTimeout(closeForm, 500);
  } catch (err:any) { setError(err?.message || "Topper save nahi ho saka."); } finally { setSaving(false); }
  }

  async function toggle(item: Topper) { setError(""); const { error } = await supabase.from("toppers").update({ active:!item.active, updated_at:new Date().toISOString() }).eq("id", item.id); if (error) setError(error.message); else await load(); }
  async function remove(item: Topper) { if (!window.confirm(`Kya aap ${item.student_name} ko toppers se permanently delete karna chahte hain?`)) return; setError(""); const { error } = await supabase.from("toppers").delete().eq("id", item.id); if (error) { setError(error.message); return; } if (item.photo_url) await deleteTopperImage(item.photo_url).catch(()=>{}); await load(); setMessage("Topper delete ho gaya."); }

  return <main className="min-h-screen bg-gray-50"><header className="border-b bg-white shadow-sm"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-5 sm:px-6 lg:px-8"><div><p className="text-sm font-bold text-green-700">Madrasa Majmaul Bahrain Bijol</p><h1 className="mt-1 text-2xl font-extrabold text-gray-900">Toppers Management</h1></div><button onClick={openAdd} className="shrink-0 rounded-xl bg-green-700 px-5 py-3 font-bold text-white shadow-sm hover:bg-green-800">+ Add Topper</button></div></header>
    <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      <div className="rounded-2xl border border-amber-100 bg-amber-50 p-5"><h2 className="font-extrabold text-amber-900">How it works</h2><p className="mt-2 text-sm leading-6 text-amber-800">Har exam ke topper ko alag record ke roop me save karein. <b>Active</b> karne par hi woh public website par Hero ke niche aur Notice Board se pehle dikhega. Inactive karte hi website se hide ho jayega.</p></div>
      {message && <div className="mt-5 rounded-xl bg-green-50 px-4 py-3 font-semibold text-green-700">{message}</div>}{error && <div className="mt-5 rounded-xl bg-red-50 px-4 py-3 font-semibold text-red-700">{error}</div>}
      {loading ? <div className="py-16 text-center text-gray-500">Loading toppers...</div> : <div className="mt-8 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{items.map(item => <div key={item.id} className="overflow-hidden rounded-3xl border border-gray-200 bg-white shadow-sm"><div className="relative h-56 bg-gray-100">{item.photo_url ? <img src={item.photo_url} alt={item.student_name} className="h-full w-full object-cover"/> : <div className="flex h-full items-center justify-center text-6xl">🎓</div>}<span className={`absolute right-4 top-4 rounded-full px-3 py-1.5 text-xs font-black ${item.active?"bg-green-600 text-white":"bg-gray-700 text-white"}`}>{item.active?"ACTIVE":"INACTIVE"}</span></div><div className="p-5"><h3 className="text-xl font-extrabold text-gray-900">{item.student_name}</h3><p className="mt-1 font-bold text-amber-600">Rank {item.rank}</p>{item.description&&<p className="mt-3 text-sm leading-6 text-gray-600">{item.description}</p>}<div className="mt-4 space-y-1 text-xs text-gray-500">{item.exam_name&&<p><b>Exam:</b> {item.exam_name}</p>}{item.course&&<p><b>Course:</b> {item.course}</p>}{item.exam_date&&<p><b>Date:</b> {new Date(`${item.exam_date}T00:00:00`).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}</p>}</div><div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>toggle(item)} className={`rounded-lg px-3 py-2 text-sm font-bold ${item.active?"bg-gray-100 text-gray-700":"bg-green-100 text-green-700"}`}>{item.active?"Make Inactive":"Make Active"}</button><button onClick={()=>openEdit(item)} className="rounded-lg bg-blue-50 px-3 py-2 text-sm font-bold text-blue-700">Edit</button><button onClick={()=>remove(item)} className="rounded-lg bg-red-50 px-3 py-2 text-sm font-bold text-red-700">Delete</button></div></div></div>)}</div>}
      {!loading && items.length===0 && <div className="mt-8 rounded-2xl border border-dashed border-gray-300 bg-white p-12 text-center text-gray-500">Abhi koi topper save nahi hai. <button onClick={openAdd} className="font-bold text-green-700">Add Topper</button></div>}
    </section>
    {showForm && <div className="fixed inset-0 z-[9999] overflow-y-auto bg-slate-950/70 p-3 backdrop-blur-sm sm:p-6"><div className="mx-auto my-3 w-full max-w-3xl overflow-hidden rounded-3xl bg-white shadow-2xl sm:my-8"><div className="border-b bg-gradient-to-r from-green-800 via-green-700 to-emerald-600 px-5 py-5 text-white sm:px-7"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[3px] text-green-100">🏆 Toppers Management</p><h2 className="mt-1 text-2xl font-extrabold">{editing?"Edit Topper":"Add New Topper"}</h2><p className="mt-1 text-sm text-green-100">Achievement details carefully fill karein</p></div><button onClick={closeForm} aria-label="Close" className="h-10 w-10 shrink-0 rounded-full bg-white/15 text-2xl leading-none text-white hover:bg-white/25">×</button></div></div><form onSubmit={save} className="max-h-[calc(100vh-150px)] overflow-y-auto p-5 sm:p-7">
      <div className="rounded-2xl border border-green-100 bg-green-50/60 p-4"><p className="text-sm font-bold text-green-900">Student Information</p><div className="mt-4 grid gap-5 sm:grid-cols-2"><label className="block"><span className="mb-2 block text-sm font-bold text-gray-700">Student Name <b className="text-red-500">*</b></span><input value={form.student_name} onChange={e=>setForm({...form,student_name:e.target.value})} placeholder="Enter student full name" required className="w-full rounded-xl border border-gray-300 bg-white px-4 py-3.5 text-gray-900 outline-none focus:border-green-600 focus:ring-2 focus:ring-green-100"/></label><label className="block"><span className="mb-2 block text-sm font-bold text-gray-700">Rank <b className="text-red-500">*</b></span><input value={form.rank} onChange={e=>setForm({...form,rank:e.target.value})} placeholder="1st / 2nd / 3rd" required className="w-full rounded-xl border border-gray-300 bg-white px-4 py-3.5 text-gray-900 outline-none focus:border-green-600 focus:ring-2 focus:ring-green-100"/></label></div></div>
      <div className="mt-5 rounded-2xl border border-gray-200 bg-white p-4 shadow-sm"><p className="text-sm font-bold text-gray-900">Student Photo</p><p className="mt-1 text-xs text-gray-500">Clear student photo upload karein. JPG, PNG ya WebP recommended.</p><div className="mt-4 flex flex-col gap-4 sm:flex-row sm:items-center"><label className="flex min-h-32 flex-1 cursor-pointer items-center justify-center rounded-2xl border-2 border-dashed border-gray-300 bg-gray-50 p-5 text-center hover:border-green-500 hover:bg-green-50/40"><input type="file" accept="image/*" onChange={e=>chooseFile(e.target.files?.[0]||null)} className="sr-only"/><span><span className="block text-3xl">📷</span><span className="mt-2 block text-sm font-bold text-gray-700">Choose photo</span><span className="mt-1 block text-xs text-gray-500">Click here to select an image</span></span></label>{(preview||form.photo_url)&&<div className="shrink-0"><img src={preview||form.photo_url} alt="Student preview" className="h-32 w-32 rounded-2xl border object-cover shadow-sm"/><p className="mt-1 text-center text-xs font-semibold text-gray-500">Preview</p></div>}</div></div>
      <div className="mt-5 rounded-2xl border border-gray-200 bg-white p-4 shadow-sm"><p className="text-sm font-bold text-gray-900">Achievement Details <span className="font-normal text-gray-400">(Optional)</span></p><div className="mt-4 space-y-5"><label className="block"><span className="mb-2 block text-sm font-bold text-gray-700">Description</span><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={4} placeholder="Achievement ya short appreciation..." className="w-full resize-y rounded-xl border border-gray-300 px-4 py-3 text-gray-900 outline-none focus:border-green-600 focus:ring-2 focus:ring-green-100"/></label><div className="grid gap-5 sm:grid-cols-3"><label className="block"><span className="mb-2 block text-sm font-bold text-gray-700">Exam Name</span><input value={form.exam_name} onChange={e=>setForm({...form,exam_name:e.target.value})} placeholder="Annual Exam" className="w-full rounded-xl border border-gray-300 px-4 py-3"/></label><label className="block"><span className="mb-2 block text-sm font-bold text-gray-700">Exam Date</span><input type="date" value={form.exam_date} onChange={e=>setForm({...form,exam_date:e.target.value})} className="w-full rounded-xl border border-gray-300 px-4 py-3"/></label><label className="block"><span className="mb-2 block text-sm font-bold text-gray-700">Course</span><input value={form.course} onChange={e=>setForm({...form,course:e.target.value})} placeholder="Hifz-ul-Quran" className="w-full rounded-xl border border-gray-300 px-4 py-3"/></label></div></div></div>
      <label className="mt-5 flex cursor-pointer items-center gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})} className="h-5 w-5 accent-green-700"/><span><b className="text-gray-900">Publish on website</b><span className="block text-xs text-gray-500">Active karne par topper public website par announcement section me dikh jayega.</span></span></label>
      {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}<div className="sticky bottom-0 -mx-5 mt-6 flex justify-end gap-3 border-t bg-white px-5 pt-5 sm:-mx-7 sm:px-7"><button type="button" onClick={closeForm} className="rounded-xl bg-gray-100 px-5 py-3 font-bold text-gray-700 hover:bg-gray-200">Cancel</button><button disabled={saving} className="rounded-xl bg-green-700 px-6 py-3 font-bold text-white shadow-sm hover:bg-green-800 disabled:cursor-not-allowed disabled:opacity-60">{saving?"Saving...":"Save Topper"}</button></div>
    </form></div></div>}
  </main>;
}
